### ISSUE TITLE
'System.Runtime' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

### ISSUE THREAD

**Issue by llehn** [themotleyfool/Klondike#157]
running 
nuget install system.runtime

gives this on the server

```
Message
An error has occurred.
ExceptionMessage
One or more errors occurred.
ExceptionType
System.AggregateException
StackTrace
at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x40ee15e0 + 0x0004f> in <filename unknown>:0 at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x40bf3e80 + 0x000ef> in <filename unknown>:0 at System.Threading.Tasks.Task.Wait () <0x40c53fc0 + 0x00030> in <filename unknown>:0 at NuGet.Lucene.LucenePackageRepository.AddPackage (IPackage package) <0x40d4a6f0 + 0x00169> in <filename unknown>:0 at NuGet.Lucene.Web.Models.DelegatingPackageRepository.AddPackage (IPackage package) <0x40d4a6b0 + 0x00027> in <filename unknown>:0 at NuGet.Lucene.Web.Models.MirroringPackageRepository.FindPackage (System.String packageId, NuGet.SemanticVersion version) <0x40cd1e80 + 0x002d0> in <filename unknown>:0 at NuGet.Lucene.Web.Controllers.PackagesController.FindPackage (NuGet.Lucene.Web.Models.PackageSpec packageSpec) <0x40d95b00 + 0x00063> in <filename unknown>:0 at NuGet.Lucene.Web.Controllers.PackagesController.DownloadPackage (System.String id, System.String version) <0x40d94ed0 + 0x000fb> in <filename unknown>:0 at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object,object[]) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor+ActionExecutor+<>c__DisplayClass10.<GetExecutor>b__9 (System.Object instance, System.Object[] methodParameters) <0x40c7e3d0 + 0x00039> in <filename unknown>:0 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor+ActionExecutor.Execute (System.Object instance, System.Object[] arguments) <0x40c7e390 + 0x0002d> in <filename unknown>:0 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync (System.Web.Http.Controllers.HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) <0x40c7d400 + 0x000b3> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at System.Web.Http.Controllers.ApiControllerActionInvoker+<InvokeActionAsyncCore>d__0.MoveNext () <0x40c7c730 + 0x00384> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at System.Web.Http.Controllers.ActionFilterResult+<ExecuteAsync>d__2.MoveNext () <0x40c7b200 + 0x005cf> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext () <0x40c79bd0 + 0x002bf> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Web.Http.Controllers.ExceptionFilterResult+<ExecuteAsync>d__0.MoveNext () <0x40c79bd0 + 0x01018> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__1.MoveNext () <0x40c664b0 + 0x005cc> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Web.Http.Dispatcher.HttpControllerDispatcher+<SendAsync>d__1.MoveNext () <0x40c664b0 + 0x00df6> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at NuGet.Lucene.Web.MessageHandlers.CrossOriginMessageHandler+<SendAsync>d__2.MoveNext () <0x40c2fd20 + 0x001ca> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at System.Web.Http.HttpServer+<SendAsync>d__0.MoveNext () <0x40c2d0a0 + 0x005e8> in <filename unknown>:0
InnerException
Message
An error has occurred.
ExceptionMessage
'System.Runtime' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
ExceptionType
System.InvalidOperationException
StackTrace
at NuGet.Manifest.ValidateDependencySets (IPackageMetadata metadata) <0x40b37b60 + 0x001c3> in <filename unknown>:0 at NuGet.Manifest.Validate (NuGet.Manifest manifest) <0x40b285b0 + 0x002af> in <filename unknown>:0 at NuGet.Manifest.ReadFrom (System.IO.Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema) <0x40b1e710 + 0x0017b> in <filename unknown>:0 at NuGet.Manifest.ReadFrom (System.IO.Stream stream, Boolean validateSchema) <0x40b1dfd0 + 0x00027> in <filename unknown>:0 at NuGet.Lucene.FastZipPackage.ProcessManifest (System.IO.Stream manifestStream) <0x40b1d850 + 0x00027> in <filename unknown>:0 at NuGet.Lucene.FastZipPackage.ProcessManifest (System.IO.Packaging.Package package) <0x40b10d70 + 0x0008a> in <filename unknown>:0 at NuGet.Lucene.FastZipPackage.Open (System.String fileLocation, System.IO.Stream stream, System.Byte[] hash) <0x40b0c930 + 0x000e8> in <filename unknown>:0 at NuGet.Lucene.FastZipPackage.Open (System.String fileLocation, System.Byte[] hash) <0x40d5d410 + 0x00063> in <filename unknown>:0 at NuGet.Lucene.LucenePackageRepository.LoadStagedPackage (NuGet.Lucene.IO.HashingWriteStream packageStream) <0x40d5cdb0 + 0x0004f> in <filename unknown>:0 at NuGet.Lucene.LucenePackageRepository+<DownloadDataServicePackage>d__55.MoveNext () <0x40d4ce70 + 0x00836> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at NuGet.Lucene.LucenePackageRepository+<DownloadOrMoveOrAddPackageToFileSystemAsync>d__53.MoveNext () <0x40d4be20 + 0x00486> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40c41200 + 0x0001f> in <filename unknown>:0 at NuGet.Lucene.LucenePackageRepository+<AddPackageAsync>d__52.MoveNext () <0x40d4b360 + 0x00248> in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x40ea9b50 + 0x00033> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x40ea97a0 + 0x00113> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x40ea96d0 + 0x000b3> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x40c12530 + 0x00042> in <filename unknown>:0 at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x40c12500 + 0x0001a> in <filename unknown>:0 at NuGet.Lucene.LucenePackageRepository+<>c__DisplayClass59_0+<<AddPackage>b__0>d.MoveNext () <0x40d4ac70 + 0x0019a> in <filename unknown>:0
```

**Comment by chriseldredge** [comment]
What version of `NuGet.exe`are you using? I've seen this problem with older clients not understanding the ever-changing and ever-breaking dependency syntax.

**Comment by llehn** [comment]
Ok my report was like the worst report ever, no details :D

I'm using nuget 3.4.4.1321
When I do this:
````nuget install System.Runtime````
here's the output of nuget:
````
Feeds used:
  https://nuget.kardex.com/api/odata/

  GET https://nuget.kardex.com/api/odata/FindPackagesById()?id='system.runtime'
  OK https://nuget.kardex.com/api/odata/FindPackagesById()?id='system.runtime' 31ms
Attempting to gather dependency information for package 'system.runtime.4.1.0' with respect to project 'C:\dev\tmp', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'system.runtime.4.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'system.runtime.4.1.0'
Resolved actions to install package 'system.runtime.4.1.0'
  GET https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content
  InternalServerError https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content 2559ms
  GET https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content
  InternalServerError https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content 2468ms
  GET https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content
  InternalServerError https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content 2683ms
Error downloading 'System.Runtime.4.1.0' from 'https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content'.
Der Antwortstatuscode gibt keinen Erfolg an: 500 (Internal Server Error).
WARNUNG: Install failed. Rolling back...
Error downloading 'System.Runtime.4.1.0' from 'https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content'.
  Der Antwortstatuscode gibt keinen Erfolg an: 500 (Internal Server Error).
````

So then I got to the url nuget complains about:
`https://nuget.kardex.com/api/packages/System.Runtime/4.1.0/content`


there I see the exception info I posted in the first post

The server is running Klondike 2

**Comment by llehn** [comment]
Upgrading nuget.core fixes the problem, see PR

**Comment by chriseldredge** [comment]
Cross referencing https://github.com/themotleyfool/NuGet.Lucene/pull/44 which has been merged and will be in the next release of Klondike.

**Comment by chriseldredge** [comment]
Fixed in v2.2.1

https://github.com/themotleyfool/Klondike/releases/tag/v2.1.1

**Comment by max-lancaster** [comment]
It seems this issue is still not resolved, my project fails the nuget package validation step with this error after I tried to upgrade to the latest version of [Autofac.Extras.Quartz](https://github.com/alphacloud/Autofac.Extras.Quartz) which depends on `System.Runtime (>= 4.3.0)`
